# Generated by Django 5.0.1 on 2024-07-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_video', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
    ]
