# Generated by Django 5.0.1 on 2024-07-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_setting_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='facebook_url',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='instagram_url',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
