# Generated by Django 5.0.6 on 2024-07-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_setting_email_setting_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='year',
        ),
        migrations.AddField(
            model_name='product',
            name='years',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
