# Generated by Django 5.0.6 on 2024-07-29 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_product_year_product_years_delete_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='car_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.carmodel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='years',
            field=models.TextField(blank=True, null=True),
        ),
    ]
