# Generated by Django 5.0.6 on 2024-07-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_setting_telegram_username_setting_wechat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
