# Generated by Django 5.0.6 on 2024-07-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_setting_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='choices',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option',
            field=models.ManyToManyField(to='core.option'),
        ),
    ]
