# Generated by Django 5.0.6 on 2024-07-30 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_option_choices_product_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='option',
            new_name='options',
        ),
    ]
