# Generated by Django 5.0.6 on 2024-08-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_orderitem_order_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('cart', 'Cart'), ('order', 'Order')], default='cart', max_length=10),
        ),
    ]
